### ISSUE TITLE
Create snakemake wrapper

### ISSUE THREAD

**Issue by mbhall88** [karel-brinda/NanoSim-H#12]
https://bitbucket.org/snakemake/snakemake-wrappers/pull-requests/70/add-nanosim-h-wrapper

**Comment by karel-brinda** [comment]
Nice!

**Comment by mbhall88** [comment]
Usage can be found at https://snakemake-wrappers.readthedocs.io/en/stable/wrappers/nanosim-h.html

**Comment by karel-brinda** [comment]
Thank you very much for the creating wrapper. Good job!
