### ISSUE TITLE
Difference between NanoSim-H and Nanosim

### ISSUE THREAD

**Issue by wyzhangMPI** [karel-brinda/NanoSim-H#5]
Hello,
    It is so great to find this useful tool for the simulaiton of ONT sequencing reads? I am wondering whether there is a big difference between NanoSim-H and NanoSim？

Thanks!

Best,
Wenyu Zhang

**Comment by karel-brinda** [comment]
Hello,

the differences are described in the readme:
* Support for Python 3
* Support for RNF read names
* Installation from PyPI
* Error profiles distributed with the main package
* Automatic testing using Travis
* Reproducible simulations (setting a seed for PRG)
* Improved interface with new parameters (e.g., for merging all contigs) and a progress bar
* Several minor bugs fixed

To sum up, the NanoSim-H package should be easier to install, should work on more computers and should provide more reproducible simulations.
