### ISSUE TITLE
creating fastq files?

### ISSUE THREAD

**Issue by nick-youngblut** [karel-brinda/NanoSim-H#6]
Is there a way to make fastq files with `nanosim-h`? It seems to me that it would be preferable to generate fastq versus fasta files, so that nanopore QC software can be run on the fastq files.

**Comment by karel-brinda** [comment]
Hi Nick, it's not currently possible, sorry for that. Nanosim-h was created as a fork of Nanosim, which lacks this functionality. In my opinion, simulating realistic base qualities is highly non-trivial in the case of nanopore.

**Comment by nick-youngblut** [comment]
Do you know of any nanopore read simulator that generates fastq (or fast5) files, or does such a tool not exist yet?

**Comment by karel-brinda** [comment]
I am not currently aware of any simulator that could do that.
